/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f0xx.h"

volatile  uint32_t Tick; // variable for SysTick

#define LED_TIME_BLINK 300 // flasher period
#define LED_TIME_SHORT 100 // short time for S2
#define LED_TIME_LONG 1000 // long time for S1
#define BUTTON_TIME_DELAY 40


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*  Add here the Interrupt Handler for the used peripheral(s) (PPP), for the  */
/*  available peripheral interrupt handler's name please refer to the startup */
void EXTI0_1_IRQHandler(void)
{
	if (EXTI->PR & EXTI_PR_PR0)
	{ // check line 0 has triggered the IT
		EXTI->PR |= EXTI_PR_PR0; // clear the pending bit
		GPIOB->ODR ^= (1<<0); // toggle LED2 at PB0
	}
}

/*Timer with SysTick*/
void SysTick_Handler(void)
{
	Tick++; // period 1ms
}

/* LED flasher*/

void flasher(void)
{
	static uint32_t delay;

	if (Tick > delay + LED_TIME_BLINK)
	{
		GPIOA->ODR ^= (1<<4);
		delay = Tick;
	}
}

void button (void)
{
	static uint32_t delay_button; // for delay 40ms
	static uint32_t off_time; // variable for counting off_time


	if (Tick > delay_button + BUTTON_TIME_DELAY)
	{
		static uint32_t old_s1; // for comparing the button
		static uint32_t old_s2; // for comparing the button
		uint32_t new_s1 = GPIOC->IDR & (1<<1); // push B1
		uint32_t new_s2 = GPIOC->IDR & (1<<0); // push B2

		/*compare the states of old and new s1 */
		/*turn the LED2 on if buttons pushed*/
		if (old_s1 && !new_s1) // falling edge
		{
			off_time = Tick + LED_TIME_LONG;
			GPIOB->BSRR = (1<<0);
		}
		old_s1 = new_s1;

		/*compare the states of old and new s2*/
		/*turn the LED2 on if buttons pushed*/
		if (old_s2 && !new_s2) // falling edge
		{
			off_time = Tick + LED_TIME_SHORT;
			GPIOB->BSRR = (1<<0);
		}
		old_s2 = new_s2;

		/*Check if it is time tu turn on the LED2*/
		if (Tick > off_time)
		{
		GPIOB->BRR = (1<<0);
		}
		delay_button = Tick;
	}
}



int main(void)
{
	/* Initialize SysTick Timer */
	SysTick_Config(8000); // 1ms

	/*Enable registers and set LEDs and PullUps*/
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN; // enable register GPIO A to B
	GPIOA->MODER |= GPIO_MODER_MODER4_0; // LED1 = PA4, output
	GPIOB->MODER |= GPIO_MODER_MODER0_0; // LED2 = PB0, output
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0; // S1 = PC1, pullup

	/* Enable Clock for SYSCFG*/
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	/* Choose Interupt source, allow mask and choose falling edge*/
	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PC; // select PC0 for EXTI0
	EXTI->IMR |= EXTI_IMR_MR0; // mask
	EXTI->FTSR |= EXTI_FTSR_TR0; // trigger on falling edge
	// NVIC_EnableIRQ(EXTI0_1_IRQn); // enable interupt request for EXTI0_1

	while(1){
		flasher();
		button();
	}

}
