/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f0xx.h"
#include "sct.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/*Call the fction we written in sct.c and set hex value to write bye on the 7-seg*/
	sct_init();
//	sct_led(0x7A5C36DE);
	while(1)
	{
		for (uint8_t i=0; i<10; i++)
		{
			sct_value(i*111);

			for(volatile uint32_t dumb_delay=0; dumb_delay<1000000; dumb_delay++)
			{}
		}
	}
}
